papi_phpers_homepage:
    path:     /
    defaults: { _controller: PapiPhpersBundle:Default:index }

papi_phpers_generate:
    path:     /generate
    defaults: { _controller: PapiPhpersBundle:Default:generate }
